# Generated by Django 3.0.3 on 2020-08-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='CVname',
            field=models.CharField(blank=True, default='MyCv', max_length=200, null=True),
        ),
    ]
